/// Flutter icons MStoreIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MStoreIcons
///      fonts:
///       - asset: fonts/MStoreIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class MStoreIcons {
  MStoreIcons._();

  static const _kFontFam = 'MStoreIcons';
  static const _kFontPkg = null;

  static const IconData code_line = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData account_circle_fill = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData account_circle_line = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bag_fill = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bag = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bell_fill = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bell = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData code_line_1 = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData contrast = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData grid_fill = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart_outline = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart_fill2 = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart2 = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home_fill = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home_line = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData house_fill = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData house = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData layout_2_fill = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData layout_2_line = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData location_outline = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData logout_circle_r_fill = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData location = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notifications = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notifications_outline = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData percent_fill = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData percent_line = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search_fill = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search_line = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings_outline = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData share_outline = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData share = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shopping_basket_2_fill = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shopping_basket_2_line = IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData star_outline = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData star = IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData store_2_fill = IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData store_2_line = IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wallet_4_line = IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wallet_3_line = IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wallet = IconData(0xe82a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_up_down_line = IconData(0xe82b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
